//  swiftlint:disable all
//
//  The code generated using DepotExport — Command line utility to export
//  colors, typography, icons and images from Figma to Xcode project.
//
//
//  Don’t edit this code manually to avoid runtime crashes
//

import SwiftUI

private class BundleProvider {
    static let bundle = Bundle.module
}

public extension ShapeStyle where Self == Color {
    static var Backdrop_backdrop_base_brighter: Color { Color("Backdrop/backdrop_base_brighter") }
    static var Backdrop_backdrop_base_brightest: Color { Color("Backdrop/backdrop_base_brightest") }
    static var Backdrop_backdrop_base_duller: Color { Color("Backdrop/backdrop_base_duller") }
    static var Backdrop_backdrop_base_dullest: Color { Color("Backdrop/backdrop_base_dullest") }
    static var Backdrop_backdrop_black: Color { Color("Backdrop/backdrop_black") }
    static var Backdrop_backdrop_four_brighter: Color { Color("Backdrop/backdrop_four_brighter") }
    static var Backdrop_backdrop_four_brightest: Color { Color("Backdrop/backdrop_four_brightest") }
    static var Backdrop_backdrop_four_duller: Color { Color("Backdrop/backdrop_four_duller") }
    static var Backdrop_backdrop_four_dullest: Color { Color("Backdrop/backdrop_four_dullest") }
    static var Backdrop_backdrop_one_brighter: Color { Color("Backdrop/backdrop_one_brighter") }
    static var Backdrop_backdrop_one_brightest: Color { Color("Backdrop/backdrop_one_brightest") }
    static var Backdrop_backdrop_one_duller: Color { Color("Backdrop/backdrop_one_duller") }
    static var Backdrop_backdrop_one_dullest: Color { Color("Backdrop/backdrop_one_dullest") }
    static var Backdrop_backdrop_primary_brighter: Color { Color("Backdrop/backdrop_primary_brighter") }
    static var Backdrop_backdrop_primary_brightest: Color { Color("Backdrop/backdrop_primary_brightest") }
    static var Backdrop_backdrop_primary_duller: Color { Color("Backdrop/backdrop_primary_duller") }
    static var Backdrop_backdrop_primary_dullest: Color { Color("Backdrop/backdrop_primary_dullest") }
    static var Backdrop_backdrop_secondary_brighter: Color { Color("Backdrop/backdrop_secondary_brighter") }
    static var Backdrop_backdrop_secondary_brightest: Color { Color("Backdrop/backdrop_secondary_brightest") }
    static var Backdrop_backdrop_secondary_duller: Color { Color("Backdrop/backdrop_secondary_duller") }
    static var Backdrop_backdrop_secondary_dullest: Color { Color("Backdrop/backdrop_secondary_dullest") }
    static var Backdrop_backdrop_tertiary_brighter: Color { Color("Backdrop/backdrop_tertiary_brighter") }
    static var Backdrop_backdrop_tertiary_brightest: Color { Color("Backdrop/backdrop_tertiary_brightest") }
    static var Backdrop_backdrop_tertiary_duller: Color { Color("Backdrop/backdrop_tertiary_duller") }
    static var Backdrop_backdrop_tertiary_dullest: Color { Color("Backdrop/backdrop_tertiary_dullest") }
    static var Backdrop_backdrop_three_brighter: Color { Color("Backdrop/backdrop_three_brighter") }
    static var Backdrop_backdrop_three_brightest: Color { Color("Backdrop/backdrop_three_brightest") }
    static var Backdrop_backdrop_three_duller: Color { Color("Backdrop/backdrop_three_duller") }
    static var Backdrop_backdrop_three_dullest: Color { Color("Backdrop/backdrop_three_dullest") }
    static var Backdrop_backdrop_two_brighter: Color { Color("Backdrop/backdrop_two_brighter") }
    static var Backdrop_backdrop_two_brightest: Color { Color("Backdrop/backdrop_two_brightest") }
    static var Backdrop_backdrop_two_duller: Color { Color("Backdrop/backdrop_two_duller") }
    static var Backdrop_backdrop_two_dullest: Color { Color("Backdrop/backdrop_two_dullest") }
    static var Backdrop_backdrop_white: Color { Color("Backdrop/backdrop_white") }
    static var Border_border_base: Color { Color("Border/border_base") }
    static var Border_border_bold: Color { Color("Border/border_bold") }
    static var Border_border_subtle: Color { Color("Border/border_subtle") }
    static var Button_button_content: Color { Color("Button/button_content") }
    static var Button_button_content_inverted: Color { Color("Button/button_content_inverted") }
    static var Button_button_destructive_background: Color { Color("Button/button_destructive_background") }
    static var Button_button_destructive_background_hover: Color { Color("Button/button_destructive_background_hover") }
    static var Button_button_destructive_background_pressed: Color { Color("Button/button_destructive_background_pressed") }
    static var Button_button_destructive_content: Color { Color("Button/button_destructive_content") }
    static var Button_button_disabled_background: Color { Color("Button/button_disabled_background") }
    static var Button_button_disabled_content: Color { Color("Button/button_disabled_content") }
    static var Button_button_primary_background: Color { Color("Button/button_primary_background") }
    static var Button_button_primary_background_hover: Color { Color("Button/button_primary_background_hover") }
    static var Button_button_primary_background_pressed: Color { Color("Button/button_primary_background_pressed") }
    static var Button_button_primary_content: Color { Color("Button/button_primary_content") }
    static var Button_button_secondary2_background: Color { Color("Button/button_secondary2_background") }
    static var Button_button_secondary2_background_hover: Color { Color("Button/button_secondary2_background_hover") }
    static var Button_button_secondary2_background_pressed: Color { Color("Button/button_secondary2_background_pressed") }
    static var Button_button_secondary2_content: Color { Color("Button/button_secondary2_content") }
    static var Button_button_secondary3_background: Color { Color("Button/button_secondary3_background") }
    static var Button_button_secondary3_background_hover: Color { Color("Button/button_secondary3_background_hover") }
    static var Button_button_secondary3_background_pressed: Color { Color("Button/button_secondary3_background_pressed") }
    static var Button_button_secondary3_content: Color { Color("Button/button_secondary3_content") }
    static var Button_button_secondary_background: Color { Color("Button/button_secondary_background") }
    static var Button_button_secondary_background_hover: Color { Color("Button/button_secondary_background_hover") }
    static var Button_button_secondary_background_pressed: Color { Color("Button/button_secondary_background_pressed") }
    static var Button_button_secondary_content: Color { Color("Button/button_secondary_content") }
    static var Button_button_tertiary_background: Color { Color("Button/button_tertiary_background") }
    static var Button_button_tertiary_background_hover: Color { Color("Button/button_tertiary_background_hover") }
    static var Button_button_tertiary_background_pressed: Color { Color("Button/button_tertiary_background_pressed") }
    static var Button_button_tertiary_border: Color { Color("Button/button_tertiary_border") }
    static var Button_button_tertiary_content: Color { Color("Button/button_tertiary_content") }
    static var Button_button_tertiary_destructive_background: Color { Color("Button/button_tertiary_destructive_background") }
    static var Button_button_tertiary_destructive_background_hover: Color { Color("Button/button_tertiary_destructive_background_hover") }
    static var Button_button_tertiary_destructive_background_pressed: Color { Color("Button/button_tertiary_destructive_background_pressed") }
    static var Button_button_tertiary_destructive_border: Color { Color("Button/button_tertiary_destructive_border") }
    static var Button_button_tertiary_destructive_content: Color { Color("Button/button_tertiary_destructive_content") }
    static var Button_button_transparent_background: Color { Color("Button/button_transparent_background") }
    static var Button_button_transparent_background_hover: Color { Color("Button/button_transparent_background_hover") }
    static var Button_button_transparent_background_pressed: Color { Color("Button/button_transparent_background_pressed") }
    static var Button_inline_textbutton_text: Color { Color("Button/inline_textbutton_text") }
    static var Button_inline_textbutton_text_inverted: Color { Color("Button/inline_textbutton_text_inverted") }
    static var CO2_co2_banner_action_icon_fill: Color { Color("CO2/co2_banner_action_icon_fill") }
    static var CO2_co2_banner_background: Color { Color("CO2/co2_banner_background") }
    static var CO2_co2_banner_background_hover: Color { Color("CO2/co2_banner_background_hover") }
    static var CO2_co2_banner_body: Color { Color("CO2/co2_banner_body") }
    static var CO2_co2_super_routes_fill: Color { Color("CO2/co2_super_routes_fill") }
    static var CarrierLogo_carrier_logo_monochrome_fill: Color { Color("CarrierLogo/carrier_logo_monochrome_fill") }
    static var Header_header_background_secondary: Color { Color("Header/header_background_secondary") }
    static var Icon_icon_fill_badge: Color { Color("Icon/icon_fill_badge") }
    static var Icon_icon_fill_base: Color { Color("Icon/icon_fill_base") }
    static var Icon_icon_fill_brand: Color { Color("Icon/icon_fill_brand") }
    static var Icon_icon_fill_disabled: Color { Color("Icon/icon_fill_disabled") }
    static var Icon_icon_fill_inverted: Color { Color("Icon/icon_fill_inverted") }
    static var Icon_icon_fill_negative: Color { Color("Icon/icon_fill_negative") }
    static var Icon_icon_fill_positive: Color { Color("Icon/icon_fill_positive") }
    static var Icon_icon_fill_subdued: Color { Color("Icon/icon_fill_subdued") }
    static var Icon_icon_fill_subdued_inverted: Color { Color("Icon/icon_fill_subdued_inverted") }
    static var Icon_icon_fill_subtle: Color { Color("Icon/icon_fill_subtle") }
    static var Icon_icon_fill_subtle_inverted: Color { Color("Icon/icon_fill_subtle_inverted") }
    static var Icon_icon_fill_urgency_high: Color { Color("Icon/icon_fill_urgency_high") }
    static var Icon_icon_fill_urgency_medium: Color { Color("Icon/icon_fill_urgency_medium") }
    static var Icon_icon_fill_warning: Color { Color("Icon/icon_fill_warning") }
    static var Link_link_base: Color { Color("Link/link_base") }
    static var Link_link_hover: Color { Color("Link/link_hover") }
    static var Link_link_pressed: Color { Color("Link/link_pressed") }
    static var Link_link_visited: Color { Color("Link/link_visited") }
    static var Loading_Skeleton_skeleton_background_base: Color { Color("Loading/Skeleton/skeleton_background_base") }
    static var Loading_Skeleton_skeleton_background_base_inverted: Color { Color("Loading/Skeleton/skeleton_background_base_inverted") }
    static var Loading_Skeleton_skeleton_background_bold: Color { Color("Loading/Skeleton/skeleton_background_bold") }
    static var Loading_Skeleton_skeleton_background_bold_inverted: Color { Color("Loading/Skeleton/skeleton_background_bold_inverted") }
    static var Loading_Spinner_spinner_background_base: Color { Color("Loading/Spinner/spinner_background_base") }
    static var Loading_Spinner_spinner_background_inverted: Color { Color("Loading/Spinner/spinner_background_inverted") }
    static var Message_message_action_icon_fill: Color { Color("Message/message_action_icon_fill") }
    static var Message_message_info_background: Color { Color("Message/message_info_background") }
    static var Message_message_info_border: Color { Color("Message/message_info_border") }
    static var Message_message_info_left_edge: Color { Color("Message/message_info_left_edge") }
    static var Message_message_negative_background: Color { Color("Message/message_negative_background") }
    static var Message_message_negative_border: Color { Color("Message/message_negative_border") }
    static var Message_message_negative_left_edge: Color { Color("Message/message_negative_left_edge") }
    static var Message_message_neutral_background: Color { Color("Message/message_neutral_background") }
    static var Message_message_neutral_border: Color { Color("Message/message_neutral_border") }
    static var Message_message_positive_background: Color { Color("Message/message_positive_background") }
    static var Message_message_positive_border: Color { Color("Message/message_positive_border") }
    static var Message_message_positive_left_edge: Color { Color("Message/message_positive_left_edge") }
    static var Message_message_primary_background: Color { Color("Message/message_primary_background") }
    static var Message_message_primary_border: Color { Color("Message/message_primary_border") }
    static var Message_message_secondary_background: Color { Color("Message/message_secondary_background") }
    static var Message_message_secondary_border: Color { Color("Message/message_secondary_border") }
    static var Message_message_warning_background: Color { Color("Message/message_warning_background") }
    static var Message_message_warning_border: Color { Color("Message/message_warning_border") }
    static var Message_message_warning_left_edge: Color { Color("Message/message_warning_left_edge") }
    static var Overlay_Bubble_bubble_background: Color { Color("Overlay/Bubble/bubble_background") }
    static var Overlay_Modal_modal_background: Color { Color("Overlay/Modal/modal_background") }
    static var Overlay_Snackbar_snackbar_background: Color { Color("Overlay/Snackbar/snackbar_background") }
    static var Overlay_Tooltip_tooltip_background: Color { Color("Overlay/Tooltip/tooltip_background") }
    static var Overlay_overlay_backdrop_one: Color { Color("Overlay/overlay_backdrop_one") }
    static var Overlay_overlay_backdrop_three: Color { Color("Overlay/overlay_backdrop_three") }
    static var Overlay_overlay_backdrop_two: Color { Color("Overlay/overlay_backdrop_two") }
    static var Overlay_overlay_background_base: Color { Color("Overlay/overlay_background_base") }
    static var Overlay_overlay_background_inverted: Color { Color("Overlay/overlay_background_inverted") }
    static var Railcard_railcard_background_16_17_one: Color { Color("Railcard/railcard_background_16_17_one") }
    static var Railcard_railcard_background_16_25_one: Color { Color("Railcard/railcard_background_16_25_one") }
    static var Railcard_railcard_background_16_25_two: Color { Color("Railcard/railcard_background_16_25_two") }
    static var Railcard_railcard_background_26_30_one: Color { Color("Railcard/railcard_background_26_30_one") }
    static var Railcard_railcard_background_26_30_two: Color { Color("Railcard/railcard_background_26_30_two") }
    static var Railcard_railcard_background_family_friends_one: Color { Color("Railcard/railcard_background_family_friends_one") }
    static var Railcard_railcard_background_family_friends_two: Color { Color("Railcard/railcard_background_family_friends_two") }
    static var Railcard_railcard_background_gold_card_one: Color { Color("Railcard/railcard_background_gold_card_one") }
    static var Railcard_railcard_background_gold_card_two: Color { Color("Railcard/railcard_background_gold_card_two") }
    static var Railcard_railcard_background_network_one: Color { Color("Railcard/railcard_background_network_one") }
    static var Railcard_railcard_background_network_two: Color { Color("Railcard/railcard_background_network_two") }
    static var Railcard_railcard_background_senior_one: Color { Color("Railcard/railcard_background_senior_one") }
    static var Railcard_railcard_background_senior_two: Color { Color("Railcard/railcard_background_senior_two") }
    static var Railcard_railcard_background_two_together_one: Color { Color("Railcard/railcard_background_two_together_one") }
    static var Railcard_railcard_background_two_together_two: Color { Color("Railcard/railcard_background_two_together_two") }
    static var Railcard_railcard_text: Color { Color("Railcard/railcard_text") }
    static var Railcard_railcard_text_inverted: Color { Color("Railcard/railcard_text_inverted") }
    static var SearchForm_search_form_background: Color { Color("SearchForm/search_form_background") }
    static var Selectable_Selected_selected_background_element: Color { Color("Selectable/Selected/selected_background_element") }
    static var Selectable_Selected_selected_background_hover: Color { Color("Selectable/Selected/selected_background_hover") }
    static var Selectable_Selected_selected_background_input: Color { Color("Selectable/Selected/selected_background_input") }
    static var Selectable_Selected_selected_background_pressed: Color { Color("Selectable/Selected/selected_background_pressed") }
    static var Selectable_Selected_selected_border_base: Color { Color("Selectable/Selected/selected_border_base") }
    static var Selectable_Selected_selected_border_hover: Color { Color("Selectable/Selected/selected_border_hover") }
    static var Selectable_Selected_selected_border_pressed: Color { Color("Selectable/Selected/selected_border_pressed") }
    static var Selectable_Selected_selected_icon_fill: Color { Color("Selectable/Selected/selected_icon_fill") }
    static var Selectable_Selected_selected_text: Color { Color("Selectable/Selected/selected_text") }
    static var Selectable_selectable_background_base: Color { Color("Selectable/selectable_background_base") }
    static var Selectable_selectable_background_disabled: Color { Color("Selectable/selectable_background_disabled") }
    static var Selectable_selectable_background_hover: Color { Color("Selectable/selectable_background_hover") }
    static var Selectable_selectable_background_pressed: Color { Color("Selectable/selectable_background_pressed") }
    static var Selectable_selectable_border_base: Color { Color("Selectable/selectable_border_base") }
    static var Selectable_selectable_border_bold: Color { Color("Selectable/selectable_border_bold") }
    static var Selectable_selectable_border_hover: Color { Color("Selectable/selectable_border_hover") }
    static var Selectable_selectable_border_invalid: Color { Color("Selectable/selectable_border_invalid") }
    static var Selectable_selectable_border_pressed: Color { Color("Selectable/selectable_border_pressed") }
    static var Selectable_selectable_text: Color { Color("Selectable/selectable_text") }
    static var Splitsave_splitsave-icon-fill: Color { Color("Splitsave/splitsave-icon-fill") }
    static var Splitsave_splitsave-text: Color { Color("Splitsave/splitsave-text") }
    static var Tag_tag_info_background: Color { Color("Tag/tag_info_background") }
    static var Tag_tag_info_border: Color { Color("Tag/tag_info_border") }
    static var Tag_tag_negative_background: Color { Color("Tag/tag_negative_background") }
    static var Tag_tag_negative_border: Color { Color("Tag/tag_negative_border") }
    static var Tag_tag_neutral_background: Color { Color("Tag/tag_neutral_background") }
    static var Tag_tag_neutral_border: Color { Color("Tag/tag_neutral_border") }
    static var Tag_tag_positive_background: Color { Color("Tag/tag_positive_background") }
    static var Tag_tag_positive_border: Color { Color("Tag/tag_positive_border") }
    static var Tag_tag_primary_background: Color { Color("Tag/tag_primary_background") }
    static var Tag_tag_primary_border: Color { Color("Tag/tag_primary_border") }
    static var Tag_tag_secondary_background: Color { Color("Tag/tag_secondary_background") }
    static var Tag_tag_secondary_border: Color { Color("Tag/tag_secondary_border") }
    static var Tag_tag_warning_background: Color { Color("Tag/tag_warning_background") }
    static var Tag_tag_warning_border: Color { Color("Tag/tag_warning_border") }
    static var TextField_textfield_background_base: Color { Color("TextField/textfield_background_base") }
    static var TextField_textfield_background_disabled: Color { Color("TextField/textfield_background_disabled") }
    static var TextField_textfield_border_base: Color { Color("TextField/textfield_border_base") }
    static var TextField_textfield_border_focus: Color { Color("TextField/textfield_border_focus") }
    static var TextField_textfield_border_hover: Color { Color("TextField/textfield_border_hover") }
    static var TextField_textfield_border_invalid: Color { Color("TextField/textfield_border_invalid") }
    static var TextField_textfield_icon_fill_base: Color { Color("TextField/textfield_icon_fill_base") }
    static var TextField_textfield_icon_fill_subtle: Color { Color("TextField/textfield_icon_fill_subtle") }
    static var TextField_textfield_label_base: Color { Color("TextField/textfield_label_base") }
    static var TextField_textfield_label_focus: Color { Color("TextField/textfield_label_focus") }
    static var TextField_textfield_placeholder: Color { Color("TextField/textfield_placeholder") }
    static var Text_text_base: Color { Color("Text/text_base") }
    static var Text_text_base_inverted: Color { Color("Text/text_base_inverted") }
    static var Text_text_brand: Color { Color("Text/text_brand") }
    static var Text_text_disabled: Color { Color("Text/text_disabled") }
    static var Text_text_negative: Color { Color("Text/text_negative") }
    static var Text_text_positive: Color { Color("Text/text_positive") }
    static var Text_text_subdued: Color { Color("Text/text_subdued") }
    static var Text_text_subdued_inverted: Color { Color("Text/text_subdued_inverted") }
    static var Text_text_subtle: Color { Color("Text/text_subtle") }
    static var Text_text_subtle_inverted: Color { Color("Text/text_subtle_inverted") }
    static var Text_text_tlb_brand_primary: Color { Color("Text/text_tlb_brand_primary") }
    static var Text_text_urgency_high: Color { Color("Text/text_urgency_high") }
    static var Text_text_urgency_medium: Color { Color("Text/text_urgency_medium") }
    static var Text_text_warning: Color { Color("Text/text_warning") }
    static var box_shadow: Color { Color("box_shadow") }
    static var focus_ring: Color { Color("focus_ring") }
    static var focus_ring_inverted: Color { Color("focus_ring_inverted") }
}
