//  swiftlint:disable all
//
//  The code generated using DepotExport — Command line utility to export
//  colors, typography, icons and images from Figma to Xcode project.
//
//
//  Don’t edit this code manually to avoid runtime crashes
//

import UIKit

private class BundleProvider {
    static let bundle = Bundle.module
}

public extension UIColor {
    static var Backdrop_backdrop_base_brighter: UIColor { UIColor(named: "Backdrop/backdrop_base_brighter")! }
    static var Backdrop_backdrop_base_brightest: UIColor { UIColor(named: "Backdrop/backdrop_base_brightest")! }
    static var Backdrop_backdrop_base_duller: UIColor { UIColor(named: "Backdrop/backdrop_base_duller")! }
    static var Backdrop_backdrop_base_dullest: UIColor { UIColor(named: "Backdrop/backdrop_base_dullest")! }
    static var Backdrop_backdrop_black: UIColor { UIColor(named: "Backdrop/backdrop_black")! }
    static var Backdrop_backdrop_four_brighter: UIColor { UIColor(named: "Backdrop/backdrop_four_brighter")! }
    static var Backdrop_backdrop_four_brightest: UIColor { UIColor(named: "Backdrop/backdrop_four_brightest")! }
    static var Backdrop_backdrop_four_duller: UIColor { UIColor(named: "Backdrop/backdrop_four_duller")! }
    static var Backdrop_backdrop_four_dullest: UIColor { UIColor(named: "Backdrop/backdrop_four_dullest")! }
    static var Backdrop_backdrop_one_brighter: UIColor { UIColor(named: "Backdrop/backdrop_one_brighter")! }
    static var Backdrop_backdrop_one_brightest: UIColor { UIColor(named: "Backdrop/backdrop_one_brightest")! }
    static var Backdrop_backdrop_one_duller: UIColor { UIColor(named: "Backdrop/backdrop_one_duller")! }
    static var Backdrop_backdrop_one_dullest: UIColor { UIColor(named: "Backdrop/backdrop_one_dullest")! }
    static var Backdrop_backdrop_primary_brighter: UIColor { UIColor(named: "Backdrop/backdrop_primary_brighter")! }
    static var Backdrop_backdrop_primary_brightest: UIColor { UIColor(named: "Backdrop/backdrop_primary_brightest")! }
    static var Backdrop_backdrop_primary_duller: UIColor { UIColor(named: "Backdrop/backdrop_primary_duller")! }
    static var Backdrop_backdrop_primary_dullest: UIColor { UIColor(named: "Backdrop/backdrop_primary_dullest")! }
    static var Backdrop_backdrop_secondary_brighter: UIColor { UIColor(named: "Backdrop/backdrop_secondary_brighter")! }
    static var Backdrop_backdrop_secondary_brightest: UIColor { UIColor(named: "Backdrop/backdrop_secondary_brightest")! }
    static var Backdrop_backdrop_secondary_duller: UIColor { UIColor(named: "Backdrop/backdrop_secondary_duller")! }
    static var Backdrop_backdrop_secondary_dullest: UIColor { UIColor(named: "Backdrop/backdrop_secondary_dullest")! }
    static var Backdrop_backdrop_tertiary_brighter: UIColor { UIColor(named: "Backdrop/backdrop_tertiary_brighter")! }
    static var Backdrop_backdrop_tertiary_brightest: UIColor { UIColor(named: "Backdrop/backdrop_tertiary_brightest")! }
    static var Backdrop_backdrop_tertiary_duller: UIColor { UIColor(named: "Backdrop/backdrop_tertiary_duller")! }
    static var Backdrop_backdrop_tertiary_dullest: UIColor { UIColor(named: "Backdrop/backdrop_tertiary_dullest")! }
    static var Backdrop_backdrop_three_brighter: UIColor { UIColor(named: "Backdrop/backdrop_three_brighter")! }
    static var Backdrop_backdrop_three_brightest: UIColor { UIColor(named: "Backdrop/backdrop_three_brightest")! }
    static var Backdrop_backdrop_three_duller: UIColor { UIColor(named: "Backdrop/backdrop_three_duller")! }
    static var Backdrop_backdrop_three_dullest: UIColor { UIColor(named: "Backdrop/backdrop_three_dullest")! }
    static var Backdrop_backdrop_two_brighter: UIColor { UIColor(named: "Backdrop/backdrop_two_brighter")! }
    static var Backdrop_backdrop_two_brightest: UIColor { UIColor(named: "Backdrop/backdrop_two_brightest")! }
    static var Backdrop_backdrop_two_duller: UIColor { UIColor(named: "Backdrop/backdrop_two_duller")! }
    static var Backdrop_backdrop_two_dullest: UIColor { UIColor(named: "Backdrop/backdrop_two_dullest")! }
    static var Backdrop_backdrop_white: UIColor { UIColor(named: "Backdrop/backdrop_white")! }
    static var Border_border_base: UIColor { UIColor(named: "Border/border_base")! }
    static var Border_border_bold: UIColor { UIColor(named: "Border/border_bold")! }
    static var Border_border_subtle: UIColor { UIColor(named: "Border/border_subtle")! }
    static var Button_button_content: UIColor { UIColor(named: "Button/button_content")! }
    static var Button_button_content_inverted: UIColor { UIColor(named: "Button/button_content_inverted")! }
    static var Button_button_destructive_background: UIColor { UIColor(named: "Button/button_destructive_background")! }
    static var Button_button_destructive_background_hover: UIColor { UIColor(named: "Button/button_destructive_background_hover")! }
    static var Button_button_destructive_background_pressed: UIColor { UIColor(named: "Button/button_destructive_background_pressed")! }
    static var Button_button_destructive_content: UIColor { UIColor(named: "Button/button_destructive_content")! }
    static var Button_button_disabled_background: UIColor { UIColor(named: "Button/button_disabled_background")! }
    static var Button_button_disabled_content: UIColor { UIColor(named: "Button/button_disabled_content")! }
    static var Button_button_primary_background: UIColor { UIColor(named: "Button/button_primary_background")! }
    static var Button_button_primary_background_hover: UIColor { UIColor(named: "Button/button_primary_background_hover")! }
    static var Button_button_primary_background_pressed: UIColor { UIColor(named: "Button/button_primary_background_pressed")! }
    static var Button_button_primary_content: UIColor { UIColor(named: "Button/button_primary_content")! }
    static var Button_button_secondary2_background: UIColor { UIColor(named: "Button/button_secondary2_background")! }
    static var Button_button_secondary2_background_hover: UIColor { UIColor(named: "Button/button_secondary2_background_hover")! }
    static var Button_button_secondary2_background_pressed: UIColor { UIColor(named: "Button/button_secondary2_background_pressed")! }
    static var Button_button_secondary2_content: UIColor { UIColor(named: "Button/button_secondary2_content")! }
    static var Button_button_secondary3_background: UIColor { UIColor(named: "Button/button_secondary3_background")! }
    static var Button_button_secondary3_background_hover: UIColor { UIColor(named: "Button/button_secondary3_background_hover")! }
    static var Button_button_secondary3_background_pressed: UIColor { UIColor(named: "Button/button_secondary3_background_pressed")! }
    static var Button_button_secondary3_content: UIColor { UIColor(named: "Button/button_secondary3_content")! }
    static var Button_button_secondary_background: UIColor { UIColor(named: "Button/button_secondary_background")! }
    static var Button_button_secondary_background_hover: UIColor { UIColor(named: "Button/button_secondary_background_hover")! }
    static var Button_button_secondary_background_pressed: UIColor { UIColor(named: "Button/button_secondary_background_pressed")! }
    static var Button_button_secondary_content: UIColor { UIColor(named: "Button/button_secondary_content")! }
    static var Button_button_tertiary_background: UIColor { UIColor(named: "Button/button_tertiary_background")! }
    static var Button_button_tertiary_background_hover: UIColor { UIColor(named: "Button/button_tertiary_background_hover")! }
    static var Button_button_tertiary_background_pressed: UIColor { UIColor(named: "Button/button_tertiary_background_pressed")! }
    static var Button_button_tertiary_border: UIColor { UIColor(named: "Button/button_tertiary_border")! }
    static var Button_button_tertiary_content: UIColor { UIColor(named: "Button/button_tertiary_content")! }
    static var Button_button_tertiary_destructive_background: UIColor { UIColor(named: "Button/button_tertiary_destructive_background")! }
    static var Button_button_tertiary_destructive_background_hover: UIColor { UIColor(named: "Button/button_tertiary_destructive_background_hover")! }
    static var Button_button_tertiary_destructive_background_pressed: UIColor { UIColor(named: "Button/button_tertiary_destructive_background_pressed")! }
    static var Button_button_tertiary_destructive_border: UIColor { UIColor(named: "Button/button_tertiary_destructive_border")! }
    static var Button_button_tertiary_destructive_content: UIColor { UIColor(named: "Button/button_tertiary_destructive_content")! }
    static var Button_button_transparent_background: UIColor { UIColor(named: "Button/button_transparent_background")! }
    static var Button_button_transparent_background_hover: UIColor { UIColor(named: "Button/button_transparent_background_hover")! }
    static var Button_button_transparent_background_pressed: UIColor { UIColor(named: "Button/button_transparent_background_pressed")! }
    static var Button_inline_textbutton_text: UIColor { UIColor(named: "Button/inline_textbutton_text")! }
    static var Button_inline_textbutton_text_inverted: UIColor { UIColor(named: "Button/inline_textbutton_text_inverted")! }
    static var CO2_co2_banner_action_icon_fill: UIColor { UIColor(named: "CO2/co2_banner_action_icon_fill")! }
    static var CO2_co2_banner_background: UIColor { UIColor(named: "CO2/co2_banner_background")! }
    static var CO2_co2_banner_background_hover: UIColor { UIColor(named: "CO2/co2_banner_background_hover")! }
    static var CO2_co2_banner_body: UIColor { UIColor(named: "CO2/co2_banner_body")! }
    static var CO2_co2_super_routes_fill: UIColor { UIColor(named: "CO2/co2_super_routes_fill")! }
    static var CarrierLogo_carrier_logo_monochrome_fill: UIColor { UIColor(named: "CarrierLogo/carrier_logo_monochrome_fill")! }
    static var Header_header_background_secondary: UIColor { UIColor(named: "Header/header_background_secondary")! }
    static var Icon_icon_fill_badge: UIColor { UIColor(named: "Icon/icon_fill_badge")! }
    static var Icon_icon_fill_base: UIColor { UIColor(named: "Icon/icon_fill_base")! }
    static var Icon_icon_fill_brand: UIColor { UIColor(named: "Icon/icon_fill_brand")! }
    static var Icon_icon_fill_disabled: UIColor { UIColor(named: "Icon/icon_fill_disabled")! }
    static var Icon_icon_fill_inverted: UIColor { UIColor(named: "Icon/icon_fill_inverted")! }
    static var Icon_icon_fill_negative: UIColor { UIColor(named: "Icon/icon_fill_negative")! }
    static var Icon_icon_fill_positive: UIColor { UIColor(named: "Icon/icon_fill_positive")! }
    static var Icon_icon_fill_subdued: UIColor { UIColor(named: "Icon/icon_fill_subdued")! }
    static var Icon_icon_fill_subdued_inverted: UIColor { UIColor(named: "Icon/icon_fill_subdued_inverted")! }
    static var Icon_icon_fill_subtle: UIColor { UIColor(named: "Icon/icon_fill_subtle")! }
    static var Icon_icon_fill_subtle_inverted: UIColor { UIColor(named: "Icon/icon_fill_subtle_inverted")! }
    static var Icon_icon_fill_urgency_high: UIColor { UIColor(named: "Icon/icon_fill_urgency_high")! }
    static var Icon_icon_fill_urgency_medium: UIColor { UIColor(named: "Icon/icon_fill_urgency_medium")! }
    static var Icon_icon_fill_warning: UIColor { UIColor(named: "Icon/icon_fill_warning")! }
    static var Link_link_base: UIColor { UIColor(named: "Link/link_base")! }
    static var Link_link_hover: UIColor { UIColor(named: "Link/link_hover")! }
    static var Link_link_pressed: UIColor { UIColor(named: "Link/link_pressed")! }
    static var Link_link_visited: UIColor { UIColor(named: "Link/link_visited")! }
    static var Loading_Skeleton_skeleton_background_base: UIColor { UIColor(named: "Loading/Skeleton/skeleton_background_base")! }
    static var Loading_Skeleton_skeleton_background_base_inverted: UIColor { UIColor(named: "Loading/Skeleton/skeleton_background_base_inverted")! }
    static var Loading_Skeleton_skeleton_background_bold: UIColor { UIColor(named: "Loading/Skeleton/skeleton_background_bold")! }
    static var Loading_Skeleton_skeleton_background_bold_inverted: UIColor { UIColor(named: "Loading/Skeleton/skeleton_background_bold_inverted")! }
    static var Loading_Spinner_spinner_background_base: UIColor { UIColor(named: "Loading/Spinner/spinner_background_base")! }
    static var Loading_Spinner_spinner_background_inverted: UIColor { UIColor(named: "Loading/Spinner/spinner_background_inverted")! }
    static var Message_message_action_icon_fill: UIColor { UIColor(named: "Message/message_action_icon_fill")! }
    static var Message_message_info_background: UIColor { UIColor(named: "Message/message_info_background")! }
    static var Message_message_info_border: UIColor { UIColor(named: "Message/message_info_border")! }
    static var Message_message_info_left_edge: UIColor { UIColor(named: "Message/message_info_left_edge")! }
    static var Message_message_negative_background: UIColor { UIColor(named: "Message/message_negative_background")! }
    static var Message_message_negative_border: UIColor { UIColor(named: "Message/message_negative_border")! }
    static var Message_message_negative_left_edge: UIColor { UIColor(named: "Message/message_negative_left_edge")! }
    static var Message_message_neutral_background: UIColor { UIColor(named: "Message/message_neutral_background")! }
    static var Message_message_neutral_border: UIColor { UIColor(named: "Message/message_neutral_border")! }
    static var Message_message_positive_background: UIColor { UIColor(named: "Message/message_positive_background")! }
    static var Message_message_positive_border: UIColor { UIColor(named: "Message/message_positive_border")! }
    static var Message_message_positive_left_edge: UIColor { UIColor(named: "Message/message_positive_left_edge")! }
    static var Message_message_primary_background: UIColor { UIColor(named: "Message/message_primary_background")! }
    static var Message_message_primary_border: UIColor { UIColor(named: "Message/message_primary_border")! }
    static var Message_message_secondary_background: UIColor { UIColor(named: "Message/message_secondary_background")! }
    static var Message_message_secondary_border: UIColor { UIColor(named: "Message/message_secondary_border")! }
    static var Message_message_warning_background: UIColor { UIColor(named: "Message/message_warning_background")! }
    static var Message_message_warning_border: UIColor { UIColor(named: "Message/message_warning_border")! }
    static var Message_message_warning_left_edge: UIColor { UIColor(named: "Message/message_warning_left_edge")! }
    static var Overlay_Bubble_bubble_background: UIColor { UIColor(named: "Overlay/Bubble/bubble_background")! }
    static var Overlay_Modal_modal_background: UIColor { UIColor(named: "Overlay/Modal/modal_background")! }
    static var Overlay_Snackbar_snackbar_background: UIColor { UIColor(named: "Overlay/Snackbar/snackbar_background")! }
    static var Overlay_Tooltip_tooltip_background: UIColor { UIColor(named: "Overlay/Tooltip/tooltip_background")! }
    static var Overlay_overlay_backdrop_one: UIColor { UIColor(named: "Overlay/overlay_backdrop_one")! }
    static var Overlay_overlay_backdrop_three: UIColor { UIColor(named: "Overlay/overlay_backdrop_three")! }
    static var Overlay_overlay_backdrop_two: UIColor { UIColor(named: "Overlay/overlay_backdrop_two")! }
    static var Overlay_overlay_background_base: UIColor { UIColor(named: "Overlay/overlay_background_base")! }
    static var Overlay_overlay_background_inverted: UIColor { UIColor(named: "Overlay/overlay_background_inverted")! }
    static var Railcard_railcard_background_16_17_one: UIColor { UIColor(named: "Railcard/railcard_background_16_17_one")! }
    static var Railcard_railcard_background_16_25_one: UIColor { UIColor(named: "Railcard/railcard_background_16_25_one")! }
    static var Railcard_railcard_background_16_25_two: UIColor { UIColor(named: "Railcard/railcard_background_16_25_two")! }
    static var Railcard_railcard_background_26_30_one: UIColor { UIColor(named: "Railcard/railcard_background_26_30_one")! }
    static var Railcard_railcard_background_26_30_two: UIColor { UIColor(named: "Railcard/railcard_background_26_30_two")! }
    static var Railcard_railcard_background_family_friends_one: UIColor { UIColor(named: "Railcard/railcard_background_family_friends_one")! }
    static var Railcard_railcard_background_family_friends_two: UIColor { UIColor(named: "Railcard/railcard_background_family_friends_two")! }
    static var Railcard_railcard_background_gold_card_one: UIColor { UIColor(named: "Railcard/railcard_background_gold_card_one")! }
    static var Railcard_railcard_background_gold_card_two: UIColor { UIColor(named: "Railcard/railcard_background_gold_card_two")! }
    static var Railcard_railcard_background_network_one: UIColor { UIColor(named: "Railcard/railcard_background_network_one")! }
    static var Railcard_railcard_background_network_two: UIColor { UIColor(named: "Railcard/railcard_background_network_two")! }
    static var Railcard_railcard_background_senior_one: UIColor { UIColor(named: "Railcard/railcard_background_senior_one")! }
    static var Railcard_railcard_background_senior_two: UIColor { UIColor(named: "Railcard/railcard_background_senior_two")! }
    static var Railcard_railcard_background_two_together_one: UIColor { UIColor(named: "Railcard/railcard_background_two_together_one")! }
    static var Railcard_railcard_background_two_together_two: UIColor { UIColor(named: "Railcard/railcard_background_two_together_two")! }
    static var Railcard_railcard_text: UIColor { UIColor(named: "Railcard/railcard_text")! }
    static var Railcard_railcard_text_inverted: UIColor { UIColor(named: "Railcard/railcard_text_inverted")! }
    static var SearchForm_search_form_background: UIColor { UIColor(named: "SearchForm/search_form_background")! }
    static var Selectable_Selected_selected_background_element: UIColor { UIColor(named: "Selectable/Selected/selected_background_element")! }
    static var Selectable_Selected_selected_background_hover: UIColor { UIColor(named: "Selectable/Selected/selected_background_hover")! }
    static var Selectable_Selected_selected_background_input: UIColor { UIColor(named: "Selectable/Selected/selected_background_input")! }
    static var Selectable_Selected_selected_background_pressed: UIColor { UIColor(named: "Selectable/Selected/selected_background_pressed")! }
    static var Selectable_Selected_selected_border_base: UIColor { UIColor(named: "Selectable/Selected/selected_border_base")! }
    static var Selectable_Selected_selected_border_hover: UIColor { UIColor(named: "Selectable/Selected/selected_border_hover")! }
    static var Selectable_Selected_selected_border_pressed: UIColor { UIColor(named: "Selectable/Selected/selected_border_pressed")! }
    static var Selectable_Selected_selected_icon_fill: UIColor { UIColor(named: "Selectable/Selected/selected_icon_fill")! }
    static var Selectable_Selected_selected_text: UIColor { UIColor(named: "Selectable/Selected/selected_text")! }
    static var Selectable_selectable_background_base: UIColor { UIColor(named: "Selectable/selectable_background_base")! }
    static var Selectable_selectable_background_disabled: UIColor { UIColor(named: "Selectable/selectable_background_disabled")! }
    static var Selectable_selectable_background_hover: UIColor { UIColor(named: "Selectable/selectable_background_hover")! }
    static var Selectable_selectable_background_pressed: UIColor { UIColor(named: "Selectable/selectable_background_pressed")! }
    static var Selectable_selectable_border_base: UIColor { UIColor(named: "Selectable/selectable_border_base")! }
    static var Selectable_selectable_border_bold: UIColor { UIColor(named: "Selectable/selectable_border_bold")! }
    static var Selectable_selectable_border_hover: UIColor { UIColor(named: "Selectable/selectable_border_hover")! }
    static var Selectable_selectable_border_invalid: UIColor { UIColor(named: "Selectable/selectable_border_invalid")! }
    static var Selectable_selectable_border_pressed: UIColor { UIColor(named: "Selectable/selectable_border_pressed")! }
    static var Selectable_selectable_text: UIColor { UIColor(named: "Selectable/selectable_text")! }
    static var Splitsave_splitsave-icon-fill: UIColor { UIColor(named: "Splitsave/splitsave-icon-fill")! }
    static var Splitsave_splitsave-text: UIColor { UIColor(named: "Splitsave/splitsave-text")! }
    static var Tag_tag_info_background: UIColor { UIColor(named: "Tag/tag_info_background")! }
    static var Tag_tag_info_border: UIColor { UIColor(named: "Tag/tag_info_border")! }
    static var Tag_tag_negative_background: UIColor { UIColor(named: "Tag/tag_negative_background")! }
    static var Tag_tag_negative_border: UIColor { UIColor(named: "Tag/tag_negative_border")! }
    static var Tag_tag_neutral_background: UIColor { UIColor(named: "Tag/tag_neutral_background")! }
    static var Tag_tag_neutral_border: UIColor { UIColor(named: "Tag/tag_neutral_border")! }
    static var Tag_tag_positive_background: UIColor { UIColor(named: "Tag/tag_positive_background")! }
    static var Tag_tag_positive_border: UIColor { UIColor(named: "Tag/tag_positive_border")! }
    static var Tag_tag_primary_background: UIColor { UIColor(named: "Tag/tag_primary_background")! }
    static var Tag_tag_primary_border: UIColor { UIColor(named: "Tag/tag_primary_border")! }
    static var Tag_tag_secondary_background: UIColor { UIColor(named: "Tag/tag_secondary_background")! }
    static var Tag_tag_secondary_border: UIColor { UIColor(named: "Tag/tag_secondary_border")! }
    static var Tag_tag_warning_background: UIColor { UIColor(named: "Tag/tag_warning_background")! }
    static var Tag_tag_warning_border: UIColor { UIColor(named: "Tag/tag_warning_border")! }
    static var TextField_textfield_background_base: UIColor { UIColor(named: "TextField/textfield_background_base")! }
    static var TextField_textfield_background_disabled: UIColor { UIColor(named: "TextField/textfield_background_disabled")! }
    static var TextField_textfield_border_base: UIColor { UIColor(named: "TextField/textfield_border_base")! }
    static var TextField_textfield_border_focus: UIColor { UIColor(named: "TextField/textfield_border_focus")! }
    static var TextField_textfield_border_hover: UIColor { UIColor(named: "TextField/textfield_border_hover")! }
    static var TextField_textfield_border_invalid: UIColor { UIColor(named: "TextField/textfield_border_invalid")! }
    static var TextField_textfield_icon_fill_base: UIColor { UIColor(named: "TextField/textfield_icon_fill_base")! }
    static var TextField_textfield_icon_fill_subtle: UIColor { UIColor(named: "TextField/textfield_icon_fill_subtle")! }
    static var TextField_textfield_label_base: UIColor { UIColor(named: "TextField/textfield_label_base")! }
    static var TextField_textfield_label_focus: UIColor { UIColor(named: "TextField/textfield_label_focus")! }
    static var TextField_textfield_placeholder: UIColor { UIColor(named: "TextField/textfield_placeholder")! }
    static var Text_text_base: UIColor { UIColor(named: "Text/text_base")! }
    static var Text_text_base_inverted: UIColor { UIColor(named: "Text/text_base_inverted")! }
    static var Text_text_brand: UIColor { UIColor(named: "Text/text_brand")! }
    static var Text_text_disabled: UIColor { UIColor(named: "Text/text_disabled")! }
    static var Text_text_negative: UIColor { UIColor(named: "Text/text_negative")! }
    static var Text_text_positive: UIColor { UIColor(named: "Text/text_positive")! }
    static var Text_text_subdued: UIColor { UIColor(named: "Text/text_subdued")! }
    static var Text_text_subdued_inverted: UIColor { UIColor(named: "Text/text_subdued_inverted")! }
    static var Text_text_subtle: UIColor { UIColor(named: "Text/text_subtle")! }
    static var Text_text_subtle_inverted: UIColor { UIColor(named: "Text/text_subtle_inverted")! }
    static var Text_text_tlb_brand_primary: UIColor { UIColor(named: "Text/text_tlb_brand_primary")! }
    static var Text_text_urgency_high: UIColor { UIColor(named: "Text/text_urgency_high")! }
    static var Text_text_urgency_medium: UIColor { UIColor(named: "Text/text_urgency_medium")! }
    static var Text_text_warning: UIColor { UIColor(named: "Text/text_warning")! }
    static var box_shadow: UIColor { UIColor(named: "box_shadow")! }
    static var focus_ring: UIColor { UIColor(named: "focus_ring")! }
    static var focus_ring_inverted: UIColor { UIColor(named: "focus_ring_inverted")! }
}
